name: LightCheck
main: ru.kainlight.lightcheck.Main
version: "2.2.1"
api-version: "1.17"

authors: [kainlight, PadowYT2]

softdepend:
  - PlaceholderAPI

commands:
  lightcheck:
    aliases:
      - check
    description: To call the player to check the cheats

permissions:
  lightcheck.list:
    default: op
  lightcheck.check:
    default: op
  lightcheck.approve:
    default: not op
  lightcheck.disprove:
    default: op
  lightcheck.timer.continue:
    default: op
  lightcheck.timer.stop:
    default: op
  lightcheck.stop-all:
    default: op
  lightcheck.reload:
    default: op
  lightcheck.admin:
    children:
      lightcheck.list: true
      lightcheck.check: true
      lightcheck.approve: true
      lightcheck.disprove: true
      lightcheck.timer.continue: true
      lightcheck.timer.stop: true
      lightcheck.stop-all: true
      lightcheck.reload: true
